// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// ONNX 모델 초기화
Future<void> initModel({required String modelPath}) =>
    RustLib.instance.api.crateApiEmbeddingInitModel(modelPath: modelPath);

/// 토큰 ID로부터 임베딩 생성
Future<Float32List> generateEmbeddingFromTokens({
  required Int64List inputIds,
  required Int64List attentionMask,
  required Int64List tokenTypeIds,
}) => RustLib.instance.api.crateApiEmbeddingGenerateEmbeddingFromTokens(
  inputIds: inputIds,
  attentionMask: attentionMask,
  tokenTypeIds: tokenTypeIds,
);

/// 텍스트에서 직접 임베딩 생성 (토큰화 + 임베딩)
Future<Float32List> embedText({required String text}) =>
    RustLib.instance.api.crateApiEmbeddingEmbedText(text: text);

/// 임베딩 차원 수 반환
int getEmbeddingDimension() =>
    RustLib.instance.api.crateApiEmbeddingGetEmbeddingDimension();
