// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EmbeddingPoint`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `distance`, `fmt`, `fmt`

/// Build HNSW index
Future<void> buildHnswIndex({
  required List<(PlatformInt64, Float32List)> points,
}) => RustLib.instance.api.crateApiHnswIndexBuildHnswIndex(points: points);

/// Search in HNSW index
Future<List<HnswSearchResult>> searchHnsw({
  required List<double> queryEmbedding,
  required BigInt topK,
}) => RustLib.instance.api.crateApiHnswIndexSearchHnsw(
  queryEmbedding: queryEmbedding,
  topK: topK,
);

/// Check if HNSW index is loaded
Future<bool> isHnswIndexLoaded() =>
    RustLib.instance.api.crateApiHnswIndexIsHnswIndexLoaded();

/// Clear HNSW index
Future<void> clearHnswIndex() =>
    RustLib.instance.api.crateApiHnswIndexClearHnswIndex();

/// HNSW search result
class HnswSearchResult {
  final PlatformInt64 id;
  final double distance;

  const HnswSearchResult({required this.id, required this.distance});

  @override
  int get hashCode => id.hashCode ^ distance.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HnswSearchResult &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          distance == other.distance;
}
